---
# Upgrade RHEL family OS packages
- name: Upgrade RHEL Family OS packages
  yum:
    name: '*'
    state: latest
    update_cache: yes
  when: ansible_os_family == "RedHat"
  become: true
  become_method: sudo
  become_user: root

- name: Update Ubuntu OS packages
  apt:
    update_cache=yes
    force_apt_get=yes
    cache_valid_time=3600
  when: ansible_os_family == "Debian"
  become: true
  become_method: sudo
  become_user: root

- name: Upgrade Ubuntu OS packages
  apt:
    upgrade=dist
    force_apt_get=yes
  when: ansible_os_family == "Debian"
  become: true
  become_method: sudo
  become_user: root

# Reboot after upgrade
- name: Reboot host
  become: true
  become_method: sudo
  become_user: root
  reboot:
    connect_timeout: "{{ reboot_connect_timeout }}"
    post_reboot_delay: "{{ reboot_post_reboot_delay }}"
    reboot_timeout: "{{ reboot_timeout }}"